[package]
name = "pf-core"
version = "0.1.0"
edition = "2024"

[dependencies]
ab_glyph = "0.2.32"
ab_glyph_rasterizer = "0.1.10"
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg", "gif", "webp", "bmp", "tiff"] }
rayon = "1.12.0"
roxmltree = "0.21.1"
thiserror = "2.0.21"
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }

[dev-dependencies]
ab_glyph = "0.2.32"
epaint_default_fonts = "0.36.2"
